name: Book Doctor Appointment
description: This form enables a nurse to capture all data required by doctor to schedule an appointment
labels: [appointment]
title: "Schedule an appointment with doctor"

body:
- type: markdown
  attributes:
    value: "![IMAGE](https://avatars.githubusercontent.com/u/111590499?s=60&v=4) Project Deserve - Book Doctor Appointment"
    
- type: input
  id: id
  attributes:
    label: Identity Number
    description: "Enter the Personal health record number for the patient"
    placeholder: "ex. xxxxxx-xxxx-xxxxx-xxxxxxx-xxxxxx"
  validations:
    required: true

- type: input
  id: weight
  attributes:
    label: Weight
    description: "Enter the current weight of the patent in kilograms"
    placeholder: "ex. 170"
  validations:
    required: true

- type: input
  id: blood_pressure
  attributes:
    label: Blood Pressure
    description: "Enter the current blod pressure of the patent"
    placeholder: "ex. xx/yy"
  validations:
    required: true

- type: input
  id: glucose_level
  attributes:
    label: Glucose Level
    description: "Enter the current temperature of the patent in mmol/L"
    placeholder: "ex. xx"
  validations:
    required: false
    
- type: input
  id: body_temperature
  attributes:
    label: Body Temperature
    description: "Enter the current temperature of the patent"
    placeholder: "ex. xx"
  validations:
    required: true

- type: dropdown
  id: reason
  attributes:
    label: Reason for the appointment
    description: "Select one of the reasons below for the reason of needing a doctor appointment"
    options:
      - Ask a Question
      - Developed a condition
      - Became ill
  validations:
    required: true

- type: dropdown
  id: condition
  attributes:
    label: Medical Condition
    description: "Select one of the medical conditions listed below"
    options:
      - c-1 - unknown
      - c-2 - yyyyyyyyyyyyy
      - c-3 - zzzzzzzzzzzzz
  validations:
    required: false

- type: dropdown
  id: illness
  attributes:
    label: Medical illness
    description: "Select one of the medical conditions listed below"
    options:
      - i-1 - unknown
      - i-2 - xxxxxxxxxxx
      - i-3 - yyyyyyyyyyy
  validations:
    required: false
    
- type: textarea
  id: additional_info
  attributes:
      label: Additional Information
      description: "Please provide as much information about the patient's current health issue"
      render: markdown   
  validations:
    required: true      
    
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: "By submitting this issue, the patient agrees to follow our [Code of Conduct(https://project-deserve.com)"
    options:
      - label: Confirmation
        required: true  
