name: Create Personal Health Record
description: This form enables a nurse to capture all data required to create a health record
labels: []
title: "Create Personal Health Record"

body:
- type: markdown
  attributes:
    value: "![IMAGE](https://avatars.githubusercontent.com/u/111590499?s=60&v=4) Project Deserve - Create Personal Health Record"
    
- type: input
  id: email
  attributes:
    label: Email Address
    description: Enter the email address for the patient
    placeholder: ex. name@domain.com     
  validations:
    required: false
    
- type: input
  id: name
  attributes:
    label: Display Name
    description: Enter the full name of the patient if permission is granted by tye patient
    placeholder: ex. Eric Olufemi Obi
  validations:
    required: false
    
- type: input
  id: birth_date
  attributes:
    label: Date of Birth
    description: Enter the date of birth
    placeholder: ex. yyyy/mm/dd
  validations:
    required: true    
    
- type: dropdown
  id: gender
  attributes:
    label: Gender
    description: Select the preffered gender      
    options:
      - Male
      - Female
      - Unknown
  validations:
    required: true    
    
- type: input
  id: weight
  attributes:
    label: Weight
    description: Enter the current weight of the patent in kilograms
    placeholder: ex. 170       
  validations:
    required: true
    
- type: input
  id: height
  attributes:
    label: Height
    description: Enter the current height of the patent in meters
    placeholder: ex. 1.2      
  validations:
    required: false
    
- type: input
  id: blood_pressure
  attributes:
    label: Blood Pressure
    description: Enter the current blood pressure of the patent
    placeholder: ex. xx/yy      
  validations:
    required: false    

- type: input
  id: glucose_level
  attributes:
    label: Glucose Level
    description: "Enter the current temperature of the patent in mmol/L"
    placeholder: "ex. xx"
  validations:
    required: false
    
- type: input
  id: body_temperature
  attributes:
    label: Body Temperature
    description: "Enter the current temperature of the patent"
    placeholder: "ex. xx"
  validations:
    required: false

- type: dropdown
  id: reason
  attributes:
    label: Reason for the appointment
    description: "Select one of the reasons below for the reason of needing a doctor appointment"
    options:
      - Ask a Question
      - Developed a condition
      - Became ill
  validations:
    required: true

- type: dropdown
  id: condition
  attributes:
    label: Medical Condition
    description: "Select one of the medical conditions listed below"
    options:
      - c-1 - unknown
      - c-2 - yyyyyyyyyyyyy
      - c-3 - zzzzzzzzzzzzz
  validations:
    required: true

- type: dropdown
  id: illness
  attributes:
    label: Medical illness
    description: "Select one of the medical conditions listed below"
    options:
      - i-1 - unknown
      - i-2 - xxxxxxxxxxx
      - i-3 - yyyyyyyyyyy
  validations:
    required: true
    
- type: textarea
  id: medical_history
  attributes:
      label: Medical History
      description: Please provide as much additional information about the patients medical history and current health issue
      render: markdown
  validations:
    required: true       
    
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: "By submitting this issue, the patient agrees to follow our [Code of Conduct(https://project-deserve.com)"
    options:
      - label: Confirmation
        required: true    
