name: Handle Health Issue
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  handle_health_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create issues JSON by parsing form           
        uses: ./.github/actions/issue-parser     
        id: parse

      - name: Process issues JSON      
        uses: ./.github/actions/issue-handler     
        id: handle
        with:
          form-data: '${{ steps.parse.outputs.data }}'   

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" &&  git config --global user.name "github-actions[bot]" && git add "Personal Health Records/readme.md" && git add "Personal Health Records/${{ steps.handle.outputs.id }}/readme.md" &&  git commit -m 'Health issue #${{github.event.issue.number}} for ${{ steps.handle.outputs.id }}' &&  git push

      - name: Create meeting link comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{github.event.issue.number}}
          body: |
            # Doctor Appointment: [${{ steps.handle.outputs.id }}][1]
            Please click [on this link][2] to meet or wait for a doctor

            [1]: https://github.com/project-deserve/clinic-alpha-one/tree/main/Personal%20Health%20Records/${{ steps.handle.outputs.id }}
            [2]: https://pade.chat:5443/ofmeet/${{ steps.handle.outputs.id }}-${{ github.event.issue.number }}
          reactions: eyes
          
      - name: Close Issue
        if: steps.handle.outputs.type != 'create' && steps.handle.outputs.type != 'update'
        uses: peter-evans/close-issue@v2
        with:
          comment: Health Issue Rejected!!         
