name: Handle Issue
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'   

      - uses: ./.github/actions/issue-parser 
        id: issue-parser-appointment
        with:
          template-path: .github/ISSUE_TEMPLATE/book-appointment.yml
          
      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > "Personal Health Records/${{ steps.issue-parser.outputs.issueparser_id }}/appointment.json"   

      - name: Commit Push
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \          
          git add "Personal Health Records/${{ steps.issue-parser.outputs.issueparser_id }}/appointment.json" && \          
          git commit -m 'New data for ${{ steps.issue-parser.outputs.issueparser_id }}' && \
          git push
