name: Handle Health Issue
on:
  issues:
    types: opened
concurrency: 'main'
jobs:
  handle_health_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - uses: ./.github/actions/issue-parser     
        id: parse
      
      - uses: ./.github/actions/issue-handler     
        id: handle
        with:
          form-data: '${{ steps.parse.outputs.data }}'   
          
      - run: echo '${{ steps.handle.outputs.readme }}'  > "Personal Health Records/${{ steps.handle.outputs.id }}/test.md"      

      - name: Commit changes
        shell: bash
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" &&  git config --global user.name "github-actions[bot]" && git add "Personal Health Records/${{ steps.handle.outputs.id }}/test.md" &&  git commit -m 'Health Issue Transaction for ${{ steps.handle.outputs.id }}' &&  git push
